os: linux
dist: focal
language: python
python:
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install -r requirements.txt

script:
  - ln -s rivalis/tests_settings.py rivalis/settings.py
  - ./clean_project.sh
  - ./manage.py collectstatic
  - coverage run -m manage test

after_success:
  - coveralls
