os: linux
dist: focal
language: python
python:
  - 3.8
  - 3.9
  - 3.10-dev
install:
  - pip install -r requirements.txt

script:
  - ln -s /home/travis/build/zetsumeishi/rivalis/rivalis/tests_settings.py /home/travis/build/zetsumeishi/rivalis/rivalis/settings.py
  - ./clean_project.sh
  - ./manage.py collectstatic
  - coverage run -m manage test

after_success:
  - coveralls
