dist: focal
language: python
python: 3.8

install:
  - pip install -r requirements.txt

script:
  - ./clean_project.sh
  - ./manage.py collectstatic
  - coverage run -m manage test --settings="rivalis.tests_settings"

after_success:
  - coveralls
